### ISSUE TITLE
css `font-stretch` is not working for Intel One Mono

### ISSUE THREAD

**Issue by cyfung1031** [intel/intel-one-mono#39]
```css
@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-regular.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-regular.woff") format("woff");
    font-weight: 400;
    font-style: normal;
}


@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-light.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-light.woff") format("woff");
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-medium.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-medium.woff") format("woff");
    font-weight: 500;
    font-style: normal;
}

@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-bold.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-bold.woff") format("woff");
    font-weight: 700;
    font-style: normal;
}



@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-italic.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-italic.woff") format("woff");
    font-weight: 400;
    font-style: italic;
}


@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-lightitalic.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-lightitalic.woff") format("woff");
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-mediumitalic.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-mediumitalic.woff") format("woff");
    font-weight: 500;
    font-style: italic;
}

@font-face {
    font-family: "Intel One Mono";
    src: url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff2/intelone-mono-font-family-bolditalic.woff2") format("woff2"),
    url("https://cdn.jsdelivr.net/gh/intel/intel-one-mono@main/fonts/woff/intelone-mono-font-family-bolditalic.woff") format("woff");
    font-weight: 700;
    font-style: italic;
}


html body {
    font-family: "Intel One Mono";
    font-stretch: 50%;
}

```

https://developer.mozilla.org/ja/docs/Web/CSS/font-stretch
